"""All-atom polymer melts with OpenMM, packmol and forcefill.

The package takes a monomer SMILES to an equilibrated melt in four steps, each
of which is usable on its own::

    from openmmpolymer import (
        ChainSpec, build_chain, assign_charges, build_polymer_forcefield,
        PackedComponent, box_edge_nm, pack_box, assemble_box, prepare_box,
        prepare_run, standard_melt_equilibration, run_protocol,
    )

    chain = build_chain(
        ChainSpec(monomer_smiles="[*]CC[*]", degree_of_polymerization=20,
                  residue_name="PE"),
        n_conformers=50,
    )
    assign_charges(chain.sdf_paths[0], "nagl")
    forcefield = build_polymer_forcefield(chain.sdf_paths[0], residue_name="PE")

    components = [PackedComponent(path, 1) for path in chain.pdb_paths]
    edge = box_edge_nm([50], [chain.molar_mass_g_mol], 0.3)
    packed = pack_box(components, edge)

    box = prepare_box(assemble_box(components, packed.packed_pdb, packed.box_nm),
                      forcefield)
    run = prepare_run(box, forcefield)
    run_protocol(standard_melt_equilibration(), run, "run")

The shape of all this follows from one constraint. forcefill will not
parameterise a residue bonded to its neighbours, and it is right not to: a
stand-alone GAFF treatment of a chain-linked residue is not valid. So a chain
is built as a single molecule and a single residue, charged here rather than by
the backend - a graph neural network scales where AM1-BCC's semi-empirical QM
does not - and packed by conformer so that the cell holds fifty different
conformations rather than fifty copies of one.

It sits next to two of the same author's packages: ``forcefill`` does the
parameterisation, and ``openmmnqe`` covers nuclear quantum effects for systems
where they matter.
"""

from importlib.metadata import PackageNotFoundError, version

from .chain import (
    ChainError,
    ChainResult,
    ChainSpec,
    assemble_chain,
    atom_names,
    backbone_path,
    build_chain,
    characteristic_ratio,
    trans_fraction,
)
from .charges import (
    CHARGE_METHODS,
    ChargeError,
    ChargeResult,
    assign_charges,
    default_nagl_model,
)
from .conformation import (
    ConformationSeries,
    EndToEndRelaxation,
    MeanSquaredDisplacement,
    PersistenceLength,
    centre_of_mass_msd,
    chain_conformation,
    end_to_end_relaxation,
    persistence_length,
)
from .correlations import (
    RadialDistribution,
    StructureFactor,
    radial_distribution,
    structure_factor,
)
from .elasticity import (
    BulkModulus,
    ElasticConsistency,
    ElasticModulus,
    PoissonRatio,
    ShearModulus,
    StressStrain,
    bulk_modulus,
    deform_stages,
    elastic_consistency,
    load_curve,
    load_stages,
    poisson_ratio,
    shear_modulus,
    shear_stages,
    stress_strain,
    youngs_modulus,
)
from .forcefield import (
    BACKENDS,
    DEFAULT_BASE_FORCEFIELD,
    ForceFieldError,
    PolymerForceField,
    build_polymer_forcefield,
    check_forcefield,
)
from .mdsystem import (
    PackedBox,
    SystemAssemblyError,
    SystemSpec,
    assemble_box,
    barostat_kind,
    build_system,
    check_box,
    check_target_density,
    check_timestep,
    find_barostat,
    make_barostat,
    max_timestep_fs,
    minimum_mass_g_mol,
    platform_is_usable,
    prepare_box,
    replicate_topology,
    select_platform,
)
from .mechanical import (
    MechanicalError,
    ModulusReport,
    ModulusResult,
    ModulusSchedule,
    ModulusSpec,
    analyse_mechanics,
    mechanical_scan,
    run_modulus_scan,
    write_mechanical_report,
)
from .packing import (
    DEFAULT_PACKING_DENSITY,
    DEFAULT_TOLERANCE_NM,
    PackedComponent,
    PackmolError,
    PackResult,
    box_edge_nm,
    check_packing,
    density_g_cm3,
    distribute_conformers,
    find_packmol,
    find_rings,
    load_positions_nm,
    pack_box,
    packmol_version,
    read_packed_pdb,
    read_pdb,
    render_packmol_input,
)
from .plots import (
    plot_conformation,
    plot_cooling_rate,
    plot_correlations,
    plot_dynamics,
    plot_moduli,
    plot_persistence,
    plot_quench_curve,
    plot_relaxation,
    plot_relaxation_spectrum,
    plot_state_data,
    plot_stress_strain,
)
from .protocols import (
    ChainDimensions,
    Protocol,
    ProtocolError,
    RunManifest,
    RunSummary,
    Stage,
    chain_dimensions,
    melt_quench,
    run_protocol,
    standard_melt_equilibration,
)
from .relaxation import (
    KWWFit,
    PronyFit,
    RelaxationCurve,
    fit_kww,
    fit_prony,
    mean_curve,
    nnls,
    prony_times_ps,
    relax_stages,
    relaxation_curve,
)
from .reporters import TrajectoryOptions, steps_for
from .simulate import (
    RELAX_MODES,
    RunContext,
    Segment,
    SimulationError,
    StageResult,
    prepare_run,
    quench_temperatures,
    relax_bin_edges_ps,
    run_anneal,
    run_compress,
    run_deform,
    run_load,
    run_minimise,
    run_npt,
    run_nvt,
    run_production,
    run_pushoff,
    run_quench,
    run_relax,
    run_segments,
    run_shear,
    safe_timestep_fs,
)
from .stress import (
    StressError,
    deviatoric_strain,
    pressure_bar,
    pressure_tensor_bar,
    stress_tensor_bar,
    tensile_stress_bar,
)
from .structure import (
    StructureReport,
    analyse_structure,
    infer_backbone,
    structure_stages,
    write_structure_report,
)
from .tg import (
    MeltEquilibration,
    ReportFiles,
    TgError,
    TgReport,
    TgResult,
    TgSchedule,
    TgSpec,
    analyse_run,
    cooling_rate_series,
    melt_equilibration,
    run_tg_scan,
    tg_coarse_scan,
    tg_fine_scan,
    write_report,
)
from .timeseries import (
    DSC_COOLING_RATE_K_PER_NS,
    EXTRAPOLATION_FORMS,
    CoolingRateExtrapolation,
    Equilibration,
    GlassTransition,
    QuenchCurve,
    StateData,
    cooling_rate_extrapolation,
    equilibration,
    glass_transition,
    quench_curve,
    quench_stages,
    read_state_data,
)
from .trajectory import (
    AnalysisError,
    Ensemble,
    Frame,
    StageFiles,
    open_run,
    stage_files,
)
from .viscoelastic import (
    LinearityCheck,
    RelaxationReport,
    RelaxationResult,
    RelaxationSchedule,
    RelaxationSpec,
    ViscoelasticError,
    analyse_relaxation,
    relax_protocol,
    relax_schedule,
    relaxation_scan,
    run_relaxation_scan,
    write_relaxation_report,
)

try:
    __version__ = version("openmmpolymer")
except PackageNotFoundError:  # pragma: no cover - uninstalled checkout
    __version__ = "0.0.0+unknown"

__all__ = [
    "BACKENDS",
    "CHARGE_METHODS",
    "DEFAULT_BASE_FORCEFIELD",
    "DEFAULT_PACKING_DENSITY",
    "DEFAULT_TOLERANCE_NM",
    "DSC_COOLING_RATE_K_PER_NS",
    "EXTRAPOLATION_FORMS",
    "RELAX_MODES",
    "AnalysisError",
    "BulkModulus",
    "ChainDimensions",
    "ChainError",
    "ChainResult",
    "ChainSpec",
    "ChargeError",
    "ChargeResult",
    "ConformationSeries",
    "CoolingRateExtrapolation",
    "ElasticConsistency",
    "ElasticModulus",
    "EndToEndRelaxation",
    "Ensemble",
    "Equilibration",
    "ForceFieldError",
    "Frame",
    "GlassTransition",
    "KWWFit",
    "LinearityCheck",
    "MeanSquaredDisplacement",
    "MechanicalError",
    "MeltEquilibration",
    "ModulusReport",
    "ModulusResult",
    "ModulusSchedule",
    "ModulusSpec",
    "PackResult",
    "PackedBox",
    "PackedComponent",
    "PackmolError",
    "PersistenceLength",
    "PoissonRatio",
    "PolymerForceField",
    "PronyFit",
    "Protocol",
    "ProtocolError",
    "QuenchCurve",
    "RadialDistribution",
    "RelaxationCurve",
    "RelaxationReport",
    "RelaxationResult",
    "RelaxationSchedule",
    "RelaxationSpec",
    "ReportFiles",
    "RunContext",
    "RunManifest",
    "RunSummary",
    "Segment",
    "ShearModulus",
    "SimulationError",
    "Stage",
    "StageFiles",
    "StageResult",
    "StateData",
    "StressError",
    "StressStrain",
    "StructureFactor",
    "StructureReport",
    "SystemAssemblyError",
    "SystemSpec",
    "TgError",
    "TgReport",
    "TgResult",
    "TgSchedule",
    "TgSpec",
    "TrajectoryOptions",
    "ViscoelasticError",
    "__version__",
    "analyse_mechanics",
    "analyse_relaxation",
    "analyse_run",
    "analyse_structure",
    "assemble_box",
    "assemble_chain",
    "assign_charges",
    "atom_names",
    "backbone_path",
    "barostat_kind",
    "box_edge_nm",
    "build_chain",
    "build_polymer_forcefield",
    "build_system",
    "bulk_modulus",
    "centre_of_mass_msd",
    "chain_conformation",
    "chain_dimensions",
    "characteristic_ratio",
    "check_box",
    "check_forcefield",
    "check_packing",
    "check_target_density",
    "check_timestep",
    "cooling_rate_extrapolation",
    "cooling_rate_series",
    "default_nagl_model",
    "deform_stages",
    "density_g_cm3",
    "deviatoric_strain",
    "distribute_conformers",
    "elastic_consistency",
    "end_to_end_relaxation",
    "equilibration",
    "find_barostat",
    "find_packmol",
    "find_rings",
    "fit_kww",
    "fit_prony",
    "glass_transition",
    "infer_backbone",
    "load_curve",
    "load_positions_nm",
    "load_stages",
    "make_barostat",
    "max_timestep_fs",
    "mean_curve",
    "mechanical_scan",
    "melt_equilibration",
    "melt_quench",
    "minimum_mass_g_mol",
    "nnls",
    "open_run",
    "pack_box",
    "packmol_version",
    "persistence_length",
    "platform_is_usable",
    "plot_conformation",
    "plot_cooling_rate",
    "plot_correlations",
    "plot_dynamics",
    "plot_moduli",
    "plot_persistence",
    "plot_quench_curve",
    "plot_relaxation",
    "plot_relaxation_spectrum",
    "plot_state_data",
    "plot_stress_strain",
    "poisson_ratio",
    "prepare_box",
    "prepare_run",
    "pressure_bar",
    "pressure_tensor_bar",
    "prony_times_ps",
    "quench_curve",
    "quench_stages",
    "quench_temperatures",
    "radial_distribution",
    "read_packed_pdb",
    "read_pdb",
    "read_state_data",
    "relax_bin_edges_ps",
    "relax_protocol",
    "relax_schedule",
    "relax_stages",
    "relaxation_curve",
    "relaxation_scan",
    "render_packmol_input",
    "replicate_topology",
    "run_anneal",
    "run_compress",
    "run_deform",
    "run_load",
    "run_minimise",
    "run_modulus_scan",
    "run_npt",
    "run_nvt",
    "run_production",
    "run_protocol",
    "run_pushoff",
    "run_quench",
    "run_relax",
    "run_relaxation_scan",
    "run_segments",
    "run_shear",
    "run_tg_scan",
    "safe_timestep_fs",
    "select_platform",
    "shear_modulus",
    "shear_stages",
    "stage_files",
    "standard_melt_equilibration",
    "steps_for",
    "stress_strain",
    "stress_tensor_bar",
    "structure_factor",
    "structure_stages",
    "tensile_stress_bar",
    "tg_coarse_scan",
    "tg_fine_scan",
    "trans_fraction",
    "write_mechanical_report",
    "write_relaxation_report",
    "write_report",
    "write_structure_report",
    "youngs_modulus",
]
