"""All-atom polymer melts with OpenMM, packmol and forcefill.

The package takes a monomer SMILES to an equilibrated melt in four steps, each
of which is usable on its own::

    from openmmpolymer import (
        ChainSpec, build_chain, assign_charges, build_polymer_forcefield,
        PackedComponent, box_edge_nm, pack_box, assemble_box, prepare_box,
        prepare_run, standard_melt_equilibration, run_protocol,
    )

    chain = build_chain(
        ChainSpec(monomer_smiles="[*]CC[*]", degree_of_polymerization=20,
                  residue_name="PE"),
        n_conformers=50,
    )
    assign_charges(chain.sdf_paths[0], "nagl")
    forcefield = build_polymer_forcefield(chain.sdf_paths[0], residue_name="PE")

    components = [PackedComponent(path, 1) for path in chain.pdb_paths]
    edge = box_edge_nm([50], [chain.molar_mass_g_mol], 0.3)
    packed = pack_box(components, edge)

    box = prepare_box(assemble_box(components, packed.packed_pdb, packed.box_nm),
                      forcefield)
    run = prepare_run(box, forcefield)
    run_protocol(standard_melt_equilibration(), run, "run")

The shape of all this follows from one constraint. forcefill will not
parameterise a residue bonded to its neighbours, and it is right not to: a
stand-alone GAFF treatment of a chain-linked residue is not valid. So a chain
is built as a single molecule and a single residue, charged here rather than by
the backend - a graph neural network scales where AM1-BCC's semi-empirical QM
does not - and packed by conformer so that the cell holds fifty different
conformations rather than fifty copies of one.

It sits next to two of the same author's packages: ``forcefill`` does the
parameterisation, and ``openmmnqe`` covers nuclear quantum effects for systems
where they matter.
"""

from importlib.metadata import PackageNotFoundError, version

from ._files import ReportFiles
from .chain import (
    ChainError,
    ChainResult,
    ChainSpec,
    assemble_chain,
    atom_names,
    backbone_path,
    build_chain,
    characteristic_ratio,
    trans_fraction,
)
from .charges import (
    CHARGE_METHODS,
    ChargeError,
    ChargeResult,
    assign_charges,
    default_nagl_model,
)
from .conformation import (
    ConformationSeries,
    EndToEndRelaxation,
    MeanSquaredDisplacement,
    PersistenceLength,
    centre_of_mass_msd,
    chain_conformation,
    end_to_end_relaxation,
    persistence_length,
)
from .convergence import (
    DEFAULT_WINDOW_FRACTIONS,
    ConvergenceReport,
    ParameterConvergence,
    RelaxationWindowConvergence,
    RelaxationWindowEstimate,
    WindowConvergence,
    WindowEstimate,
    analyse_convergence,
    relaxation_window_convergence,
    time_window_convergence,
)
from .convergence_report import (
    plot_relaxation_convergence,
    plot_structural_convergence,
    plot_window_convergence,
    write_convergence_report,
)
from .correlations import (
    RadialDistribution,
    StructureFactor,
    radial_distribution,
    structure_factor,
)
from .elastic_rates import (
    ELASTIC_RATE_PROPERTIES,
    ElasticRatePlan,
    analyse_elastic_rates,
    run_elastic_rate_scan,
    validate_elastic_rate_scan,
)
from .elasticity import (
    BulkModulus,
    ElasticConsistency,
    ElasticModulus,
    PoissonRatio,
    ShearModulus,
    StressStrain,
    bulk_modulus,
    deform_stages,
    elastic_consistency,
    load_curve,
    load_stages,
    poisson_ratio,
    shear_modulus,
    shear_stages,
    stress_strain,
    youngs_modulus,
)
from .forcefield import (
    BACKENDS,
    DEFAULT_BASE_FORCEFIELD,
    ForceFieldError,
    PolymerForceField,
    build_polymer_forcefield,
    check_forcefield,
)
from .mdsystem import (
    PackedBox,
    SystemAssemblyError,
    SystemSpec,
    assemble_box,
    barostat_kind,
    build_system,
    check_box,
    check_target_density,
    check_timestep,
    find_barostat,
    make_barostat,
    max_timestep_fs,
    minimum_mass_g_mol,
    platform_is_usable,
    prepare_box,
    replicate_topology,
    select_platform,
)
from .mechanical import (
    MechanicalError,
    ModulusReport,
    ModulusResult,
    ModulusSchedule,
    ModulusSpec,
    analyse_mechanics,
    mechanical_scan,
    run_modulus_scan,
    write_mechanical_report,
)
from .modulus_rate_report import write_modulus_rate_report
from .modulus_rates import (
    ModulusRatePlan,
    ModulusRateReport,
    analyse_modulus_rates,
    run_modulus_rate_scan,
    validate_modulus_rate_scan,
)
from .packing import (
    DEFAULT_PACKING_DENSITY,
    DEFAULT_TOLERANCE_NM,
    PackedComponent,
    PackmolError,
    PackResult,
    box_edge_nm,
    check_packing,
    density_g_cm3,
    distribute_conformers,
    find_packmol,
    find_rings,
    load_positions_nm,
    pack_box,
    packmol_version,
    read_packed_pdb,
    read_pdb,
    render_packmol_input,
)
from .plots import (
    plot_breaking_strength,
    plot_conformation,
    plot_cooling_rate,
    plot_correlations,
    plot_dynamics,
    plot_elongation_at_break,
    plot_moduli,
    plot_persistence,
    plot_quench_curve,
    plot_relaxation,
    plot_relaxation_spectrum,
    plot_state_data,
    plot_strain_rate,
    plot_stress_strain,
    plot_yield_strength,
)
from .property_rates import (
    RATE_PROPERTIES,
    analyse_property_rates,
    default_rate_spec,
    run_property_rate_scan,
    validate_property_rate_scan,
)
from .protocols import (
    ChainDimensions,
    Protocol,
    ProtocolError,
    RunManifest,
    RunSummary,
    Stage,
    chain_dimensions,
    melt_quench,
    run_protocol,
    standard_melt_equilibration,
)
from .rate_dependence import (
    RateExtrapolation,
    RateObservation,
    RateProperty,
    RateReport,
    analyse_rate_observations,
    rate_extrapolation,
)
from .rate_reports import plot_rate_dependence, write_rate_report
from .relaxation import (
    KWWFit,
    PronyFit,
    RelaxationCurve,
    fit_kww,
    fit_prony,
    mean_curve,
    nnls,
    prony_times_ps,
    relax_stages,
    relaxation_curve,
)
from .reporters import TrajectoryOptions, steps_for
from .simulate import (
    RELAX_MODES,
    RunContext,
    Segment,
    SimulationError,
    StageResult,
    heating_temperatures,
    prepare_run,
    quench_temperatures,
    relax_bin_edges_ps,
    run_anneal,
    run_compress,
    run_deform,
    run_heat,
    run_load,
    run_minimise,
    run_npt,
    run_nvt,
    run_production,
    run_pushoff,
    run_quench,
    run_relax,
    run_segments,
    run_shear,
    safe_timestep_fs,
)
from .strain_rate import StrainRateExtrapolation, strain_rate_extrapolation
from .strength import (
    BreakingStrength,
    ElongationAtBreak,
    YieldStrength,
    breaking_strength,
    elongation_at_break,
    yield_strength,
)
from .stress import (
    StressError,
    deviatoric_strain,
    pressure_bar,
    pressure_tensor_bar,
    stress_tensor_bar,
    tensile_stress_bar,
)
from .structural_convergence import (
    StructuralParameterConvergence,
    StructuralWindow,
    StructuralWindowConvergence,
    structural_window_convergence,
)
from .structure import (
    StructureReport,
    analyse_structure,
    infer_backbone,
    structure_stages,
    write_structure_report,
)
from .tensile import (
    BreakingError,
    BreakingReport,
    BreakingSpec,
    ElongationError,
    ElongationReport,
    ElongationSpec,
    TensileSchedule,
    TensileSpec,
    YieldError,
    YieldReport,
    YieldSpec,
    analyse_breaking,
    analyse_elongation,
    analyse_yield,
    breaking_stages,
    elongation_stages,
    run_breaking_scan,
    run_elongation_scan,
    run_yield_scan,
    tensile_protocol,
    tensile_scan,
    tensile_schedule,
    write_breaking_report,
    write_elongation_report,
    write_yield_report,
    yield_stages,
)
from .tensile_rates import (
    TENSILE_RATE_PROPERTIES,
    TensileRatePlan,
    analyse_tensile_rates,
    run_tensile_rate_scan,
    validate_tensile_rate_scan,
)
from .tg import (
    MeltEquilibration,
    TgError,
    TgReport,
    TgResult,
    TgSchedule,
    TgSpec,
    analyse_run,
    cooling_rate_series,
    melt_equilibration,
    run_tg_scan,
    tg_coarse_scan,
    tg_fine_scan,
    write_report,
)
from .thermal_rates import (
    THERMAL_RATE_PROPERTIES,
    ThermalRateError,
    ThermalRatePlan,
    analyse_thermal_rates,
    run_thermal_rate_scan,
    validate_thermal_rate_scan,
)
from .timeseries import (
    DSC_COOLING_RATE_K_PER_NS,
    EXTRAPOLATION_FORMS,
    CoolingRateExtrapolation,
    Equilibration,
    GlassTransition,
    QuenchCurve,
    StateData,
    cooling_rate_extrapolation,
    equilibration,
    glass_transition,
    quench_curve,
    quench_stages,
    read_state_data,
)
from .tm import (
    HeatingCurve,
    MeltingReport,
    MeltingTransition,
    TmError,
    TmResult,
    TmSpec,
    analyse_melting,
    heating_curve,
    heating_stages,
    melting_scan,
    melting_temperature,
    run_tm_scan,
    write_melting_report,
)
from .trajectory import (
    AnalysisError,
    Ensemble,
    Frame,
    StageFiles,
    open_run,
    stage_files,
)
from .viscoelastic import (
    LinearityCheck,
    RelaxationReport,
    RelaxationResult,
    RelaxationSchedule,
    RelaxationSpec,
    ViscoelasticError,
    analyse_relaxation,
    relax_protocol,
    relax_schedule,
    relaxation_scan,
    run_relaxation_scan,
    write_relaxation_report,
)

try:
    __version__ = version("openmmpolymer")
except PackageNotFoundError:  # pragma: no cover - uninstalled checkout
    __version__ = "0.0.0+unknown"

__all__ = [
    "BACKENDS",
    "CHARGE_METHODS",
    "DEFAULT_BASE_FORCEFIELD",
    "DEFAULT_PACKING_DENSITY",
    "DEFAULT_TOLERANCE_NM",
    "DEFAULT_WINDOW_FRACTIONS",
    "DSC_COOLING_RATE_K_PER_NS",
    "ELASTIC_RATE_PROPERTIES",
    "EXTRAPOLATION_FORMS",
    "RATE_PROPERTIES",
    "RELAX_MODES",
    "TENSILE_RATE_PROPERTIES",
    "THERMAL_RATE_PROPERTIES",
    "AnalysisError",
    "BreakingError",
    "BreakingReport",
    "BreakingSpec",
    "BreakingStrength",
    "BulkModulus",
    "ChainDimensions",
    "ChainError",
    "ChainResult",
    "ChainSpec",
    "ChargeError",
    "ChargeResult",
    "ConformationSeries",
    "ConvergenceReport",
    "CoolingRateExtrapolation",
    "ElasticConsistency",
    "ElasticModulus",
    "ElasticRatePlan",
    "ElongationAtBreak",
    "ElongationError",
    "ElongationReport",
    "ElongationSpec",
    "EndToEndRelaxation",
    "Ensemble",
    "Equilibration",
    "ForceFieldError",
    "Frame",
    "GlassTransition",
    "HeatingCurve",
    "KWWFit",
    "LinearityCheck",
    "MeanSquaredDisplacement",
    "MechanicalError",
    "MeltEquilibration",
    "MeltingReport",
    "MeltingTransition",
    "ModulusRatePlan",
    "ModulusRateReport",
    "ModulusReport",
    "ModulusResult",
    "ModulusSchedule",
    "ModulusSpec",
    "PackResult",
    "PackedBox",
    "PackedComponent",
    "PackmolError",
    "ParameterConvergence",
    "PersistenceLength",
    "PoissonRatio",
    "PolymerForceField",
    "PronyFit",
    "Protocol",
    "ProtocolError",
    "QuenchCurve",
    "RadialDistribution",
    "RateExtrapolation",
    "RateObservation",
    "RateProperty",
    "RateReport",
    "RelaxationCurve",
    "RelaxationReport",
    "RelaxationResult",
    "RelaxationSchedule",
    "RelaxationSpec",
    "RelaxationWindowConvergence",
    "RelaxationWindowEstimate",
    "ReportFiles",
    "RunContext",
    "RunManifest",
    "RunSummary",
    "Segment",
    "ShearModulus",
    "SimulationError",
    "Stage",
    "StageFiles",
    "StageResult",
    "StateData",
    "StrainRateExtrapolation",
    "StressError",
    "StressStrain",
    "StructuralParameterConvergence",
    "StructuralWindow",
    "StructuralWindowConvergence",
    "StructureFactor",
    "StructureReport",
    "SystemAssemblyError",
    "SystemSpec",
    "TensileRatePlan",
    "TensileSchedule",
    "TensileSpec",
    "TgError",
    "TgReport",
    "TgResult",
    "TgSchedule",
    "TgSpec",
    "ThermalRateError",
    "ThermalRatePlan",
    "TmError",
    "TmResult",
    "TmSpec",
    "TrajectoryOptions",
    "ViscoelasticError",
    "WindowConvergence",
    "WindowEstimate",
    "YieldError",
    "YieldReport",
    "YieldSpec",
    "YieldStrength",
    "__version__",
    "analyse_breaking",
    "analyse_convergence",
    "analyse_elastic_rates",
    "analyse_elongation",
    "analyse_mechanics",
    "analyse_melting",
    "analyse_modulus_rates",
    "analyse_property_rates",
    "analyse_rate_observations",
    "analyse_relaxation",
    "analyse_run",
    "analyse_structure",
    "analyse_tensile_rates",
    "analyse_thermal_rates",
    "analyse_yield",
    "assemble_box",
    "assemble_chain",
    "assign_charges",
    "atom_names",
    "backbone_path",
    "barostat_kind",
    "box_edge_nm",
    "breaking_stages",
    "breaking_strength",
    "build_chain",
    "build_polymer_forcefield",
    "build_system",
    "bulk_modulus",
    "centre_of_mass_msd",
    "chain_conformation",
    "chain_dimensions",
    "characteristic_ratio",
    "check_box",
    "check_forcefield",
    "check_packing",
    "check_target_density",
    "check_timestep",
    "cooling_rate_extrapolation",
    "cooling_rate_series",
    "default_nagl_model",
    "default_rate_spec",
    "deform_stages",
    "density_g_cm3",
    "deviatoric_strain",
    "distribute_conformers",
    "elastic_consistency",
    "elongation_at_break",
    "elongation_stages",
    "end_to_end_relaxation",
    "equilibration",
    "find_barostat",
    "find_packmol",
    "find_rings",
    "fit_kww",
    "fit_prony",
    "glass_transition",
    "heating_curve",
    "heating_stages",
    "heating_temperatures",
    "infer_backbone",
    "load_curve",
    "load_positions_nm",
    "load_stages",
    "make_barostat",
    "max_timestep_fs",
    "mean_curve",
    "mechanical_scan",
    "melt_equilibration",
    "melt_quench",
    "melting_scan",
    "melting_temperature",
    "minimum_mass_g_mol",
    "nnls",
    "open_run",
    "pack_box",
    "packmol_version",
    "persistence_length",
    "platform_is_usable",
    "plot_breaking_strength",
    "plot_conformation",
    "plot_cooling_rate",
    "plot_correlations",
    "plot_dynamics",
    "plot_elongation_at_break",
    "plot_moduli",
    "plot_persistence",
    "plot_quench_curve",
    "plot_rate_dependence",
    "plot_relaxation",
    "plot_relaxation_convergence",
    "plot_relaxation_spectrum",
    "plot_state_data",
    "plot_strain_rate",
    "plot_stress_strain",
    "plot_structural_convergence",
    "plot_window_convergence",
    "plot_yield_strength",
    "poisson_ratio",
    "prepare_box",
    "prepare_run",
    "pressure_bar",
    "pressure_tensor_bar",
    "prony_times_ps",
    "quench_curve",
    "quench_stages",
    "quench_temperatures",
    "radial_distribution",
    "rate_extrapolation",
    "read_packed_pdb",
    "read_pdb",
    "read_state_data",
    "relax_bin_edges_ps",
    "relax_protocol",
    "relax_schedule",
    "relax_stages",
    "relaxation_curve",
    "relaxation_scan",
    "relaxation_window_convergence",
    "render_packmol_input",
    "replicate_topology",
    "run_anneal",
    "run_breaking_scan",
    "run_compress",
    "run_deform",
    "run_elastic_rate_scan",
    "run_elongation_scan",
    "run_heat",
    "run_load",
    "run_minimise",
    "run_modulus_rate_scan",
    "run_modulus_scan",
    "run_npt",
    "run_nvt",
    "run_production",
    "run_property_rate_scan",
    "run_protocol",
    "run_pushoff",
    "run_quench",
    "run_relax",
    "run_relaxation_scan",
    "run_segments",
    "run_shear",
    "run_tensile_rate_scan",
    "run_tg_scan",
    "run_thermal_rate_scan",
    "run_tm_scan",
    "run_yield_scan",
    "safe_timestep_fs",
    "select_platform",
    "shear_modulus",
    "shear_stages",
    "stage_files",
    "standard_melt_equilibration",
    "steps_for",
    "strain_rate_extrapolation",
    "stress_strain",
    "stress_tensor_bar",
    "structural_window_convergence",
    "structure_factor",
    "structure_stages",
    "tensile_protocol",
    "tensile_scan",
    "tensile_schedule",
    "tensile_stress_bar",
    "tg_coarse_scan",
    "tg_fine_scan",
    "time_window_convergence",
    "trans_fraction",
    "validate_elastic_rate_scan",
    "validate_modulus_rate_scan",
    "validate_property_rate_scan",
    "validate_tensile_rate_scan",
    "validate_thermal_rate_scan",
    "write_breaking_report",
    "write_convergence_report",
    "write_elongation_report",
    "write_mechanical_report",
    "write_melting_report",
    "write_modulus_rate_report",
    "write_rate_report",
    "write_relaxation_report",
    "write_report",
    "write_structure_report",
    "write_yield_report",
    "yield_stages",
    "yield_strength",
    "youngs_modulus",
]
